version: '3.8'

services:

  db:
    container_name: pg
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: damazio
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: blog
    ports:
      - "5432:5432"

